#Forest hyperparameters
# Param. description; Integer
tree_depth = 10
# Param. description; Integer
min_sample_split = 4
# Param. description; Integer
tree_min_leaf_samples = 1
# Param. description; Integer
num_of_trees = 20
# Currently not used
# rel_max_leaf_node_pruning = None
# Param. description; Integer
max_leaf_nodes = None
# Param. description; ('balanced','balanced_subsample',None)
class_weight = 'balanced_subsample'
# Param. description; ['auto','log2','sqrt']
max_feature_parameter = 'log2'
# Param. description; Float; Between 0 and 1 included
max_feature_cont_parameter = 0.362233199721295
# Param. description; (True, False)
bootstrap_parameter = True
# Param. description; Float; Range ?
min_impurity_decrease_exp = 11.7787
# Param. description; (True, False)
oob_score = False
# Param. description; Float; Range ?
ccp_alpha_exp = 30
# Param. description; Float; Between 0 and 1 included
max_sample_parameter = 0.9276380091150952
# Param. description; Integer
number_of_bins = 2
# Param. description; Float; Range ?
# p_val_thresh = 0.81533
# Param. description; Float; Range ?
# sample_weight_parameter = 1.0
# Param. description; Float; [0, 20]
reg_alpha_exp = 3.5
# Param. description; Float; [-1, 20]
reg_c_exp = 3.
# Param. description; Float; Range ?
reg_thresh_exp = 20.
# Param. description; Float; Between 0 and 1 included
confusion_goodwill = 0.3720368
# Param. description; Integer; [0, 'max']??
list_ranking_thresh = 150