def initFeatures(samples):
    samples.addFeature('Distance-based classification','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('Distance-based simple classification','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('RIN-based classification','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('RIN-based simple classification','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('Classification confidence','real',group='structural',default_value=0.)
    samples.addFeature('Structure location','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('Mainchain location','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('Sidechain location','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('RSA','real',group='structural',default_value=2.0)
    samples.addFeature('Mainchain RSA','real',group='structural',default_value=2.0)
    samples.addFeature('Sidechain RSA','real',group='structural',default_value=2.0)
    samples.addFeature('Amount of mapped structures','integer',group='structural',default_value=0)
    samples.addFeature('Secondary structure assignment','categorical',group='structural',default_value='Not mapped')
    samples.addFeature('IUPred value','real',group='amino acid property',default_value=0.)
    samples.addFeature('Region structure type','categorical',group='amino acid property',default_value=None)
    samples.addFeature('Modres score','real',group='structural',default_value=0.)
    samples.addFeature('Modres probability','real',group='structural',default_value='0.')
    samples.addFeature('Phi','real',group='structural',default_value='0.')
    samples.addFeature('Psi','real',group='structural',default_value='0.')
    samples.addFeature('RSA change score','real',group='structural',default_value='0.')
    samples.addFeature('Mainchain RSA change score','real',group='structural',default_value='0.')
    samples.addFeature('Sidechain RSA change score','real',group='structural',default_value='0.')

    for chaintype in ['mc','sc']:
        for interaction_type in ['neighbor','short','long','ligand','ion','metal','Protein','DNA','RNA','Peptide']:
            feature_name = '%s %s score' % (chaintype,interaction_type)
            samples.addFeature(feature_name,'real',group='structural',default_value=0.)
            feature_name = '%s %s degree' % (chaintype,interaction_type)
            samples.addFeature(feature_name,'integer',group='structural',default_value=0)
            feature_name = '%s %s H-bond score' % (chaintype,interaction_type)
            samples.addFeature(feature_name,'real',group='structural',default_value=0.)

    samples.addFeature('KD mean','real',group='amino acid property',default_value='0.',mutation_specific=True)
    samples.addFeature('Volume mean','real',group='amino acid property',default_value='0.',mutation_specific=True)
    samples.addFeature('Chemical distance','real',group='amino acid property',default_value='0.',mutation_specific=True)
    samples.addFeature('Blosum62','real',group='amino acid property',default_value='0.',mutation_specific=True)

    samples.addFeature('Aliphatic change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Hydrophobic change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Aromatic change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Positive charged change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Polar change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Negative charge change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Charged change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Small change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Tiny change','binary',group='amino acid property',mutation_specific=True)
    samples.addFeature('Total change','binary',group='amino acid property',mutation_specific=True)

    samples.addFeature('Wildtype AA','categorical',group = 'amino acid property')
    samples.addFeature('Mutant AA','categorical',group = 'amino acid property',mutation_specific=True)
    samples.addFeature('AA change','categorical',group = 'amino acid property',mutation_specific=True)

    samples.addFeature('B Factor','real',group='structural',default_value=0.)

    samples.addFeature('AbsoluteCentrality','real',group='structural',default_value=0.)
    samples.addFeature('LengthNormalizedCentrality','real',group='structural',default_value=0.)
    samples.addFeature('MinMaxNormalizedCentrality','real',group='structural',default_value=0.)
    samples.addFeature('AbsoluteCentralityWithNegative','real',group='structural',default_value=0.)
    samples.addFeature('LengthNormalizedCentralityWithNegative','real',group='structural',default_value=0.)
    samples.addFeature('MinMaxNormalizedCentralityWithNegative','real',group='structural',default_value=0.)
    samples.addFeature('AbsoluteComplexCentrality','real',group='structural',default_value=0.)
    samples.addFeature('LengthNormalizedComplexCentrality','real',group='structural',default_value=0.)
    samples.addFeature('MinMaxNormalizedComplexCentrality','real',group='structural',default_value=0.)
    samples.addFeature('AbsoluteComplexCentralityWithNegative','real',group='structural',default_value=0.)
    samples.addFeature('LengthNormalizedComplexCentralityWithNegative','real',group='structural',default_value=0.)
    samples.addFeature('MinMaxNormalizedComplexCentralityWithNegative','real',group='structural',default_value=0.)

    samples.addFeature('Intra_SSBOND_Propensity','real',group='structural',default_value=0.)
    samples.addFeature('Inter_SSBOND_Propensity','real',group='structural',default_value=0.)
    samples.addFeature('Intra_Link_Propensity','real',group='structural',default_value=0.)
    samples.addFeature('Inter_Link_Propensity','real',group='structural',default_value=0.)
    samples.addFeature('CIS_Conformation_Propensity','real',group='structural',default_value=0.)
    samples.addFeature('CIS_Follower_Propensity','real',group='structural',default_value=0.)

    samples.addFeature('Inter Chain Median KD','real',group = 'structural',default_value=0.)
    samples.addFeature('Inter Chain Distance Weighted KD','real',group = 'structural',default_value=0.)
    samples.addFeature('Inter Chain Median RSA','real',group = 'structural',default_value=0.)
    samples.addFeature('Inter Chain Distance Weighted RSA','real',group = 'structural',default_value=0.)

    samples.addFeature('Intra Chain Median KD','real',group = 'structural',default_value=0.)
    samples.addFeature('Intra Chain Distance Weighted KD','real',group = 'structural',default_value=0.)
    samples.addFeature('Intra Chain Median RSA','real',group = 'structural',default_value=0.)
    samples.addFeature('Intra Chain Distance Weighted RSA','real',group = 'structural',default_value=0.)

    samples.addFeature('Inter Chain Interactions Median','real', group = 'structural',default_value=0.)
    samples.addFeature('Inter Chain Interactions Distance Weighted','real',group = 'structural',default_value=0.)
    samples.addFeature('Intra Chain Interactions Median','real', group = 'structural',default_value=0.)
    samples.addFeature('Intra Chain Interactions Distance Weighted','real',group = 'structural',default_value=0.)
